/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    'index.html',
    'src/js/**/*.js',
    'src/js/*.js',
  ],
  theme: {
    colors: {
      'current': 'currentColor',
      'transparent': 'transparent',
      'black': '#000',
      'white': '#fff',
      'dark': '#262C6C',
      'green': '#93BCB4',
      'grey': '#F5EEF5',
      'red': '#CA3432',
      orange: {
        900: '#F89958',
        300: '#FDDFCB',
        200: '#FFE9D0',
        100: '#FEF5EE',
      },
      violet: {
        900: '#686CB2',
        200: '#E6D0E5',
      },
    },
    fontFamily: {
      default: [
        '"Poppins"',
        'sans-serif',
      ],
    }, 
    fontSize: {
      'xs': '12px',
      'xs-1': '14px',
      's': '16px',
      base: '18px',
      'm': '20px',
      'm-1l': '22px',
      'm-1': '24px',
      'm-2': '28px',
      'ml': '32px',
      'ml-1': '36px',
      'ml-2': '40px',
      'ml-5': '48px',
      'l': '56px',
      'xl': '70px',
    },
    lineHeight: {
      10: '1',
      103: '1.03',
      115: '1.15',
      12: '1.2',
      125: '1.25',
      128: '1.28',
      129: '1.29',
      149: '1.49',
      15: '1.5',
    },
    letterSpacing: {
      'none': '0',
      'sm': '0.02em',
      'md': '0.05em',
    },
    spacing: {
      0: '0px',
      1: '1px',
    },
    borderRadius: {
      'none': '0',
      'xs': '2px',
      's': '8px',
      's1': '10px',
      's2': '15px',
      DEFAULT: '20px',
      'sm': '35px',
      'm': '40px',
      'm1': '42px',
      'm2': '50px',
      'm3': '56px',
      'sl': '67px',
      'full': '9999px',
    },
    screens: {
      // => @media (min-width: ..px) { ... }
      'mobile': '540px',
      'tablet': '768px',
      'laptop': '1024px',
      'laptop-xl': '1280px',
      'desktop': '1440px',
      'large': '1800px',
      // => @media (max-width: ..px) { ... }
      "mobile-tablet": { max: "767px" },
      "mobile-laptop": { max: "1023px" },
      "mobile-desktop": { max: "1439px" },
    },
    container: {
      center: true,
      padding: '16px',
      screens: {
        DEFAULT: '100%',
        // md: '1332px',
        // xl: '1632px',
      },
    },
    extend: {},
  },
  plugins: [],
}
